name: Scrape TEFAS Fund Data

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 12 PM GMT+3 (9 AM UTC) every day

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull changes from remote branch
      run: git pull origin data

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update fund data"
        branch: data
        create_branch: true
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}